[mycloud]
type = s3
provider = Other
access_key_id = AKIATNXVV4W1M5B7B1D9
secret_access_key = M=YXXKMQMXRUL1CTSPPTB97ZS1254EPGV0ZAQW5L
region =
endpoint = s3.cstcloud.cn
acl = private
force_path_style = true
